name: Auto Merge

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  flag-pr:
    runs-on: ubuntu-22.04
    steps:
      - name: Flag PR as Auto Mergeable
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: gh pr merge --auto --squash "$PR_URL"
