name: Lint Markdown

on: push

jobs:
  markdown-lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Setup Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: 3.11

      - name: Setup uv
        uses: astral-sh/setup-uv@023eb7875fa1caa15814da58d1df7350f8fb1fd9 # v3.1.3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: markdownlint
        run: uv run --locked --only-dev pymarkdown scan .
