name: Check Python Formatting

on: push

jobs:
  ruff-format-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Setup Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: 3.11

      - name: Setup uv
        uses: astral-sh/setup-uv@abac0ce7b0768476333db78faaf98b1130f5face # v3.1.1
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: ruff format check
        run: uv run --locked --only-dev ruff format --check
