name: Lint Shell Scripts

on: push

jobs:
  shellcheck-lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Shellcheck
        uses: reviewdog/action-shellcheck@ccaafec556ffa154f112bfcb7b9c9574190b7091 # v1.27.0
        with:
          level: error
          filter_mode: nofilter
